version: '3.7'

services:

  web:
    image: httpd:latest
    container_name: website
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs  # Corregido el directorio de volumen

  mysql_db_container:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: codo_codo
      MYSQL_DATABASE: reserva_db
    ports:
      - "3309:3307"  # Puerto modificado para evitar conflictos

  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    ports:
      - "8080:8080"  # Puerto modificado para evitar conflicto con el servicio web
    
